export type ChangeKind = "new" | "fix" | "improved" | "soon";
export type ChangeEntry = { date: string; kind: ChangeKind; title: string; detail?: string };

export const CHANGELOG: ChangeEntry[] = [
  { date: "2026-06-04", kind: "fix", title: "Featured event posters load publicly", detail: "Uploaded poster images are now served via a long-lived signed URL so they appear on the banner for every visitor." },
  { date: "2026-06-04", kind: "new", title: "Featured banner countdown", detail: "If a featured event has a start time, the banner shows a live countdown (days/hours/minutes/seconds) until the stream goes live." },
  { date: "2026-06-04", kind: "fix", title: "Feature flags actually hide tabs", detail: "Toggling Podcasts / Radio / Live Sports / Watch Party in the admin now hides them on the public home immediately." },
  { date: "2026-06-04", kind: "fix", title: "Player no longer squished on mobile", detail: "Removed the outer aspect-video wrapper that was shrinking the stream behind the toolbar. The player is back to a clean full-width 16:9 frame." },
  { date: "2026-06-04", kind: "fix", title: "Radio country picker redesigned", detail: "Replaced the native browser picker with a branded matte-black searchable sheet, sorted A-Z." },
  { date: "2026-06-04", kind: "improved", title: "Watch Party — clearer flow", detail: "Inline errors when a URL or code is missing and a 'Try with a sample movie' shortcut so hosting a room always works on the first click." },
  { date: "2026-06-04", kind: "new", title: "Capacitor scaffold + native downloads", detail: "Added capacitor.config.ts and a downloadToDevice helper. Inside the Android APK shell, downloads write straight to the device's Downloads folder; web users keep the existing mirror flow." },
  { date: "2026-06-04", kind: "new", title: "Multi-host deployment configs", detail: "Added _redirects, netlify.toml and DEPLOYMENT.md so the static bundle deploys cleanly to Cloudflare Pages, Netlify, Vercel, Render and GitHub Pages." },
  { date: "2026-06-03", kind: "fix", title: "Feature flags now apply for everyone", detail: "Toggles in DEV OPTIONS propagate to every visitor within ~30s instead of being stuck behind a permanent client cache." },
  { date: "2026-06-03", kind: "fix", title: "Featured event poster upload", detail: "Admin can now upload an image file directly (Lovable Cloud storage bucket) instead of pasting an image URL — banners refresh for live visitors every 30s." },
  { date: "2026-06-03", kind: "fix", title: "Live TV: all countries by default", detail: "Opening Live TV no longer locks to India. Default is a shuffled mix from every country, and the country picker has been redesigned as a branded matte-black searchable sheet." },
  { date: "2026-06-03", kind: "fix", title: "Mobile player full-bleed", detail: "Phone players now fill the screen edge-to-edge in a true 16:9 frame — no more side margins or black letterboxing." },
  { date: "2026-06-03", kind: "improved", title: "Auto-play next: runtime fallback", detail: "If the embed never reports focus, the Up Next countdown still fires after the episode runtime so autoplay always triggers." },
  { date: "2026-06-03", kind: "fix", title: "Watch Party: clearer errors", detail: "Create / Join buttons now show an inline hint when the URL or room code is missing instead of silently doing nothing." },
  { date: "2026-06-03", kind: "new", title: "Admin: feature flags + featured events", detail: "DEV OPTIONS now has a Flags & Events tab — toggle major features ON/OFF instantly for every visitor and publish promotional banners (matches, premieres) to the home page with schedule + priority." },
  { date: "2026-06-03", kind: "fix", title: "Podcasts: featured by default", detail: "Podcasts page now loads a fresh random pool of trending shows instead of an empty 'search any podcast' state." },
  { date: "2026-06-03", kind: "fix", title: "Permanent matte-black + orange theme", detail: "Removed the light/dark toggle and stripped the blue fallback palette — the original LACZEK matte-black design is now the single source of truth and can't auto-switch on any device." },
  { date: "2026-06-03", kind: "new", title: "Advanced search & filters", detail: "Live suggestions as you type (movies, shows and people), plus genre, year, rating and sort filters. Click an actor to discover everything they're in." },
  { date: "2026-06-03", kind: "new", title: "Auto-play next + Skip Recap + PiP", detail: "TV episodes now auto-advance with a 10s countdown, a Skip Recap (+90s) button is in the player header, and Picture-in-Picture is one tap away (falls back to a floating popup window)." },
  { date: "2026-06-03", kind: "new", title: "Watch Party rooms", detail: "Host a synced viewing room, share an invite link, chat live with friends while you watch." },
  { date: "2026-06-03", kind: "improved", title: "Live Sports cards", detail: "Team badges, posters and kickoff times; streams split into Live now vs Upcoming." },
  { date: "2026-06-03", kind: "improved", title: "Radio: every country", detail: "Country list now pulled live from Radio Browser — every country with stations is listed." },
  { date: "2026-06-03", kind: "fix", title: "Podcasts UX", detail: "Search starts empty (no auto 'daily news') and each show can load more episodes beyond the first 20." },
  { date: "2026-06-03", kind: "new", title: "Live Sports expansion", detail: "NBA, NFL, MLB, NHL, F1, UFC and Tennis tabs with live scores, upcoming fixtures and final results — powered by ESPN's public feed." },
  { date: "2026-06-03", kind: "improved", title: "Radio & Podcasts moved to Home tabs", detail: "Find them alongside CCTV — sticky players, mobile-first layout, and a more reliable podcast feed loader." },
  { date: "2026-06-03", kind: "fix", title: "Podcasts playback", detail: "Rewrote the episode player with proper Audio lifecycle, multi-proxy RSS fallback and per-episode play/pause." },
  { date: "2026-06-02", kind: "new", title: "Radio worldwide", detail: "Stream thousands of free radio stations from anywhere — sticky player keeps playing while you browse." },
  { date: "2026-06-02", kind: "new", title: "Podcasts", detail: "Search, browse and play podcasts. Episodes pulled from public iTunes / RSS feeds." },
  { date: "2026-06-02", kind: "new", title: "Speed test in menu", detail: "Quick built-in internet speed test using Cloudflare's public endpoint." },
  { date: "2026-06-02", kind: "new", title: "Download the app", detail: "Install LaCzek Stream as a PWA or grab the Android APK from the menu." },
  { date: "2026-06-02", kind: "new", title: "Updates channel", detail: "Quick link to the LaCzek Telegram channel for live announcements." },
  { date: "2026-06-02", kind: "improved", title: "Renamed Football tab → Live Sports", detail: "Groundwork for upcoming NBA, NFL, F1, UFC, tennis and more." },
  { date: "—", kind: "soon", title: "Actors & Cast system", detail: "Full /actor/:id pages, cast carousels, actor search, trending actors via TMDB." },
  { date: "—", kind: "soon", title: "AI Developer Agent", detail: "Hidden admin dashboard with log scanner, AI chat and patch previews." },
  { date: "—", kind: "soon", title: "Play-by-play stadium view", detail: "Real-time pitch visualization with events, attack direction & momentum." },
  { date: "—", kind: "soon", title: "Featured events CMS & feature toggles", detail: "Admin can highlight matches/movies and enable/disable features instantly." },
  { date: "—", kind: "soon", title: "Kids profile & parental controls" },
  { date: "—", kind: "soon", title: "Recaps, autoplay next, mobile fill mode, PiP" },
  { date: "2026-05-05", kind: "new", title: "DEV OPTIONS panel", detail: "Real-time visitor analytics with country, time spent, current page and watch history — auto-refreshes every 5 seconds." },
  { date: "2026-05-05", kind: "new", title: "Slide-in navigation drawer", detail: "Cleaner, faster menu that slides in from the right." },
  { date: "2026-05-05", kind: "new", title: "Language selector", detail: "Pick from 70+ languages." },
  { date: "2026-05-05", kind: "new", title: "Live football search", detail: "Find a stream by team or league." },
  { date: "2026-05-05", kind: "new", title: "What's New page", detail: "See everything that ships." },
  { date: "2026-05-05", kind: "improved", title: "Auto-switch broken servers", detail: "If a stream doesn't start within 30s, the next server is loaded automatically." },
  { date: "2026-05-05", kind: "fix", title: "Visitor tracking now works", detail: "All sessions, page views and searches are saved in the cloud." },
  { date: "2026-05-04", kind: "new", title: "Silent ad / popup blocker", detail: "Direct-link redirects from streams are blocked transparently." },
  { date: "2026-05-03", kind: "new", title: "Live match chat", detail: "Real-time chat panel inside every football live stream." },
  { date: "2026-05-02", kind: "fix", title: "Football streams audio restored" },
  { date: "2026-05-02", kind: "improved", title: "Notify-me for upcoming matches" },
  { date: "—", kind: "soon", title: "Full UI translations", detail: "Wiring the language picker into every label." },
  { date: "—", kind: "soon", title: "User accounts & cloud watchlist", detail: "Sync your library across devices." },
  { date: "—", kind: "soon", title: "PiP & Cast support" },
];