export const QA_LIST: { q: string; a: string }[] = [
  { q: "Is LACZEK STREAMs free?", a: "Yes — every section (movies, TV, football, music, CCTV) is 100% free." },
  { q: "Do I need an account?", a: "No account is required. Start streaming right away." },
  { q: "Why does some content fail to play?", a: "We aggregate public sources. If one server is down, switch to another server in the player sidebar." },
  { q: "Can I download movies?", a: "Yes — open any movie and use the Download mirrors in the sidebar to save it to your device." },
  { q: "Can I cast to my TV?", a: "Use your browser's built-in cast feature (Chrome → Cast) once playback starts." },
  { q: "Why are there ads sometimes?", a: "Public stream providers may inject ads. We sandbox the football player to block pop-ups." },
  { q: "Is it safe to use?", a: "We never collect personal data. All preferences live only in your browser." },
  { q: "How do I change my default tab?", a: "Set during onboarding, or use the menu → Browse genres / specific tab to navigate." },
  { q: "How do I switch to light mode?", a: "Open the 3-dot menu and tap 'Light mode' / 'Dark mode'." },
  { q: "Can I get notified when a match starts?", a: "Yes — tap the Notify button on any scheduled match. Allow notifications when prompted." },
  { q: "Why does the football stream take a few seconds?", a: "Sources buffer the live feed. The 30-second countdown ends as soon as playback starts." },
  { q: "Can I watch on mobile?", a: "Absolutely — the entire site is mobile-first with a Fill-screen button for landscape playback." },
  { q: "How do I clear my watch history?", a: "Open the 3-dot menu → 'Clear my data'." },
  { q: "Can I export my watchlist?", a: "Yes — 3-dot menu → 'Export my library' downloads a JSON backup." },
  { q: "Why does CCTV use YouTube embeds?", a: "Most public CCTV is published as YouTube Live, giving us reliable global streams." },
  { q: "How fresh are the football streams?", a: "Live and updated continuously. Refresh the page to pull the latest source list." },
  { q: "What's 'Surprise me'?", a: "It launches a random popular movie — perfect when you can't decide what to watch." },
  { q: "Are quality settings real?", a: "Most embed providers control quality automatically based on your bandwidth. The selector is a hint." },
  { q: "How do I report a broken stream?", a: "Use the bug button (bottom-left) — it sends a WhatsApp message straight to the developer." },
  { q: "Who built LACZEK STREAMs?", a: "LACZEK TITUS — see the Developer section in the menu for socials." },
];