/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnblockedMoviesRouteImport } from './routes/unblocked-movies'
import { Route as SpeedtestRouteImport } from './routes/speedtest'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as PartyRouteImport } from './routes/party'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartyRoomIdRouteImport } from './routes/party.$roomId'
import { Route as FootballStreamMatchIdRouteImport } from './routes/football-stream.$matchId'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime.$animeId'
import { Route as WatchKindIdRouteImport } from './routes/watch.$kind.$id'
import { Route as ApiPublicPodcastFeedRouteImport } from './routes/api.public.podcast-feed'
import { Route as ApiPublicFootballStreamsRouteImport } from './routes/api.public.football-streams'
import { Route as ApiPublicChangelogImageRouteImport } from './routes/api.public.changelog-image'
import { Route as ApiPublicCctvCamerasRouteImport } from './routes/api.public.cctv-cameras'
import { Route as ApiPublicAnimeVideoRouteImport } from './routes/api.public.anime-video'
import { Route as ApiPublicAnimeProxyRouteImport } from './routes/api.public.anime-proxy'
import { Route as ApiPublicAnimeImageRouteImport } from './routes/api.public.anime-image'
import { Route as ApiPublicAdminStorageSignRouteImport } from './routes/api.public.admin-storage-sign'

const UnblockedMoviesRoute = UnblockedMoviesRouteImport.update({
  id: '/unblocked-movies',
  path: '/unblocked-movies',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedtestRoute = SpeedtestRouteImport.update({
  id: '/speedtest',
  path: '/speedtest',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoute = PartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoomIdRoute = PartyRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => PartyRoute,
} as any)
const FootballStreamMatchIdRoute = FootballStreamMatchIdRouteImport.update({
  id: '/football-stream/$matchId',
  path: '/football-stream/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchKindIdRoute = WatchKindIdRouteImport.update({
  id: '/watch/$kind/$id',
  path: '/watch/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPodcastFeedRoute = ApiPublicPodcastFeedRouteImport.update({
  id: '/api/public/podcast-feed',
  path: '/api/public/podcast-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFootballStreamsRoute =
  ApiPublicFootballStreamsRouteImport.update({
    id: '/api/public/football-streams',
    path: '/api/public/football-streams',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChangelogImageRoute = ApiPublicChangelogImageRouteImport.update({
  id: '/api/public/changelog-image',
  path: '/api/public/changelog-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCctvCamerasRoute = ApiPublicCctvCamerasRouteImport.update({
  id: '/api/public/cctv-cameras',
  path: '/api/public/cctv-cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnimeVideoRoute = ApiPublicAnimeVideoRouteImport.update({
  id: '/api/public/anime-video',
  path: '/api/public/anime-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnimeProxyRoute = ApiPublicAnimeProxyRouteImport.update({
  id: '/api/public/anime-proxy',
  path: '/api/public/anime-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnimeImageRoute = ApiPublicAnimeImageRouteImport.update({
  id: '/api/public/anime-image',
  path: '/api/public/anime-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminStorageSignRoute =
  ApiPublicAdminStorageSignRouteImport.update({
    id: '/api/public/admin-storage-sign',
    path: '/api/public/admin-storage-sign',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/party': typeof PartyRouteWithChildren
  '/podcasts': typeof PodcastsRoute
  '/radio': typeof RadioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speedtest': typeof SpeedtestRoute
  '/unblocked-movies': typeof UnblockedMoviesRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/football-stream/$matchId': typeof FootballStreamMatchIdRoute
  '/party/$roomId': typeof PartyRoomIdRoute
  '/api/public/admin-storage-sign': typeof ApiPublicAdminStorageSignRoute
  '/api/public/anime-image': typeof ApiPublicAnimeImageRoute
  '/api/public/anime-proxy': typeof ApiPublicAnimeProxyRoute
  '/api/public/anime-video': typeof ApiPublicAnimeVideoRoute
  '/api/public/cctv-cameras': typeof ApiPublicCctvCamerasRoute
  '/api/public/changelog-image': typeof ApiPublicChangelogImageRoute
  '/api/public/football-streams': typeof ApiPublicFootballStreamsRoute
  '/api/public/podcast-feed': typeof ApiPublicPodcastFeedRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/party': typeof PartyRouteWithChildren
  '/podcasts': typeof PodcastsRoute
  '/radio': typeof RadioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speedtest': typeof SpeedtestRoute
  '/unblocked-movies': typeof UnblockedMoviesRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/football-stream/$matchId': typeof FootballStreamMatchIdRoute
  '/party/$roomId': typeof PartyRoomIdRoute
  '/api/public/admin-storage-sign': typeof ApiPublicAdminStorageSignRoute
  '/api/public/anime-image': typeof ApiPublicAnimeImageRoute
  '/api/public/anime-proxy': typeof ApiPublicAnimeProxyRoute
  '/api/public/anime-video': typeof ApiPublicAnimeVideoRoute
  '/api/public/cctv-cameras': typeof ApiPublicCctvCamerasRoute
  '/api/public/changelog-image': typeof ApiPublicChangelogImageRoute
  '/api/public/football-streams': typeof ApiPublicFootballStreamsRoute
  '/api/public/podcast-feed': typeof ApiPublicPodcastFeedRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/party': typeof PartyRouteWithChildren
  '/podcasts': typeof PodcastsRoute
  '/radio': typeof RadioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speedtest': typeof SpeedtestRoute
  '/unblocked-movies': typeof UnblockedMoviesRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/football-stream/$matchId': typeof FootballStreamMatchIdRoute
  '/party/$roomId': typeof PartyRoomIdRoute
  '/api/public/admin-storage-sign': typeof ApiPublicAdminStorageSignRoute
  '/api/public/anime-image': typeof ApiPublicAnimeImageRoute
  '/api/public/anime-proxy': typeof ApiPublicAnimeProxyRoute
  '/api/public/anime-video': typeof ApiPublicAnimeVideoRoute
  '/api/public/cctv-cameras': typeof ApiPublicCctvCamerasRoute
  '/api/public/changelog-image': typeof ApiPublicChangelogImageRoute
  '/api/public/football-streams': typeof ApiPublicFootballStreamsRoute
  '/api/public/podcast-feed': typeof ApiPublicPodcastFeedRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/party'
    | '/podcasts'
    | '/radio'
    | '/sitemap.xml'
    | '/speedtest'
    | '/unblocked-movies'
    | '/anime/$animeId'
    | '/football-stream/$matchId'
    | '/party/$roomId'
    | '/api/public/admin-storage-sign'
    | '/api/public/anime-image'
    | '/api/public/anime-proxy'
    | '/api/public/anime-video'
    | '/api/public/cctv-cameras'
    | '/api/public/changelog-image'
    | '/api/public/football-streams'
    | '/api/public/podcast-feed'
    | '/watch/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/party'
    | '/podcasts'
    | '/radio'
    | '/sitemap.xml'
    | '/speedtest'
    | '/unblocked-movies'
    | '/anime/$animeId'
    | '/football-stream/$matchId'
    | '/party/$roomId'
    | '/api/public/admin-storage-sign'
    | '/api/public/anime-image'
    | '/api/public/anime-proxy'
    | '/api/public/anime-video'
    | '/api/public/cctv-cameras'
    | '/api/public/changelog-image'
    | '/api/public/football-streams'
    | '/api/public/podcast-feed'
    | '/watch/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/party'
    | '/podcasts'
    | '/radio'
    | '/sitemap.xml'
    | '/speedtest'
    | '/unblocked-movies'
    | '/anime/$animeId'
    | '/football-stream/$matchId'
    | '/party/$roomId'
    | '/api/public/admin-storage-sign'
    | '/api/public/anime-image'
    | '/api/public/anime-proxy'
    | '/api/public/anime-video'
    | '/api/public/cctv-cameras'
    | '/api/public/changelog-image'
    | '/api/public/football-streams'
    | '/api/public/podcast-feed'
    | '/watch/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  PartyRoute: typeof PartyRouteWithChildren
  PodcastsRoute: typeof PodcastsRoute
  RadioRoute: typeof RadioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeedtestRoute: typeof SpeedtestRoute
  UnblockedMoviesRoute: typeof UnblockedMoviesRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRoute
  FootballStreamMatchIdRoute: typeof FootballStreamMatchIdRoute
  ApiPublicAdminStorageSignRoute: typeof ApiPublicAdminStorageSignRoute
  ApiPublicAnimeImageRoute: typeof ApiPublicAnimeImageRoute
  ApiPublicAnimeProxyRoute: typeof ApiPublicAnimeProxyRoute
  ApiPublicAnimeVideoRoute: typeof ApiPublicAnimeVideoRoute
  ApiPublicCctvCamerasRoute: typeof ApiPublicCctvCamerasRoute
  ApiPublicChangelogImageRoute: typeof ApiPublicChangelogImageRoute
  ApiPublicFootballStreamsRoute: typeof ApiPublicFootballStreamsRoute
  ApiPublicPodcastFeedRoute: typeof ApiPublicPodcastFeedRoute
  WatchKindIdRoute: typeof WatchKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unblocked-movies': {
      id: '/unblocked-movies'
      path: '/unblocked-movies'
      fullPath: '/unblocked-movies'
      preLoaderRoute: typeof UnblockedMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speedtest': {
      id: '/speedtest'
      path: '/speedtest'
      fullPath: '/speedtest'
      preLoaderRoute: typeof SpeedtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$roomId': {
      id: '/party/$roomId'
      path: '/$roomId'
      fullPath: '/party/$roomId'
      preLoaderRoute: typeof PartyRoomIdRouteImport
      parentRoute: typeof PartyRoute
    }
    '/football-stream/$matchId': {
      id: '/football-stream/$matchId'
      path: '/football-stream/$matchId'
      fullPath: '/football-stream/$matchId'
      preLoaderRoute: typeof FootballStreamMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$kind/$id': {
      id: '/watch/$kind/$id'
      path: '/watch/$kind/$id'
      fullPath: '/watch/$kind/$id'
      preLoaderRoute: typeof WatchKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/podcast-feed': {
      id: '/api/public/podcast-feed'
      path: '/api/public/podcast-feed'
      fullPath: '/api/public/podcast-feed'
      preLoaderRoute: typeof ApiPublicPodcastFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-streams': {
      id: '/api/public/football-streams'
      path: '/api/public/football-streams'
      fullPath: '/api/public/football-streams'
      preLoaderRoute: typeof ApiPublicFootballStreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/changelog-image': {
      id: '/api/public/changelog-image'
      path: '/api/public/changelog-image'
      fullPath: '/api/public/changelog-image'
      preLoaderRoute: typeof ApiPublicChangelogImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cctv-cameras': {
      id: '/api/public/cctv-cameras'
      path: '/api/public/cctv-cameras'
      fullPath: '/api/public/cctv-cameras'
      preLoaderRoute: typeof ApiPublicCctvCamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anime-video': {
      id: '/api/public/anime-video'
      path: '/api/public/anime-video'
      fullPath: '/api/public/anime-video'
      preLoaderRoute: typeof ApiPublicAnimeVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anime-proxy': {
      id: '/api/public/anime-proxy'
      path: '/api/public/anime-proxy'
      fullPath: '/api/public/anime-proxy'
      preLoaderRoute: typeof ApiPublicAnimeProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anime-image': {
      id: '/api/public/anime-image'
      path: '/api/public/anime-image'
      fullPath: '/api/public/anime-image'
      preLoaderRoute: typeof ApiPublicAnimeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-storage-sign': {
      id: '/api/public/admin-storage-sign'
      path: '/api/public/admin-storage-sign'
      fullPath: '/api/public/admin-storage-sign'
      preLoaderRoute: typeof ApiPublicAdminStorageSignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PartyRouteChildren {
  PartyRoomIdRoute: typeof PartyRoomIdRoute
}

const PartyRouteChildren: PartyRouteChildren = {
  PartyRoomIdRoute: PartyRoomIdRoute,
}

const PartyRouteWithChildren = PartyRoute._addFileChildren(PartyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  PartyRoute: PartyRouteWithChildren,
  PodcastsRoute: PodcastsRoute,
  RadioRoute: RadioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeedtestRoute: SpeedtestRoute,
  UnblockedMoviesRoute: UnblockedMoviesRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRoute,
  FootballStreamMatchIdRoute: FootballStreamMatchIdRoute,
  ApiPublicAdminStorageSignRoute: ApiPublicAdminStorageSignRoute,
  ApiPublicAnimeImageRoute: ApiPublicAnimeImageRoute,
  ApiPublicAnimeProxyRoute: ApiPublicAnimeProxyRoute,
  ApiPublicAnimeVideoRoute: ApiPublicAnimeVideoRoute,
  ApiPublicCctvCamerasRoute: ApiPublicCctvCamerasRoute,
  ApiPublicChangelogImageRoute: ApiPublicChangelogImageRoute,
  ApiPublicFootballStreamsRoute: ApiPublicFootballStreamsRoute,
  ApiPublicPodcastFeedRoute: ApiPublicPodcastFeedRoute,
  WatchKindIdRoute: WatchKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
